<?php

use Illuminate\Database\Seeder;
use App\Supplier as Supplier;
use App\SupplierContact as SupplierContact;

  
class SupplierTableSeeder extends Seeder {
  
    public function run() {
        //User::truncate();
        DB::Table('suppliers')->delete();
  
        //Supplier::create(['supplier_name' => '1010 Printing Australia']);
        //Supplier::create(['supplier_name' => 'Abel Labels']);

        foreach(explode("\n", "1010 PRINTING AUSTRALIA
3L ELECTRONICS CO (SHEN ZHEN)
7 DAYS PRINT
ABEL LABELS
ACE GRAPHICS & PRINT PTY LTD
AD-MAG FRIDGE MAGNETS
ADHESIVE MAGNETIC SUPPLIES PTY LTD
AGILITY LOGISTICS
ALLKOTES (VIC) PTY LTD
ANHUI PROVINCE TAIHU ZEHONG PLASTIC CO LTD
ANHUI TECHNOLOGY IMP & EXP CO LTD
AO XIANG GREEN SHOPPING BAG
ART AND SOUL
ASIA PACIFIC OFFSET
AUS ELECTRICAL SERVICES
AWM ELECTRICAL
B&H KING MOLD LIMITED
BADGER MAKES BADGES PTY LTD
BANNER CITY PTY LTD
BASS STRAIT TRANSPORT
BEE PRINTING CO LTD
BETTER FINISH CO LTD
BILTON GRAPHICS PTY LTD
BIRK AND BLYME PTY LTD
BLD SUPERIOR BAG CO LTD
BOLG
BRAYMAN GRAPHIC ENGINEERS PTY LTD
BURELA INSTRUMENTATION PTY LTD
C AND C OFFSET PRINTING CO LTD AUSTRALIA
CANGNAN WELL BAGS CO LTD
CARDPRO AUSTRALIA
CARR GROUP
CENTRUM PRINTING
CHAINZONE TECHNOLOGY (FOSHAN) CO LTD
CHANGCHUN TONG HUI TRADING CO LTD
CHANGZHOU HUAPU CORK PRODUCTS CO LTD
CHANGZHOU K K LIGHTING ELECTRIC CO LTD
CHANGZHOU QUALITY FLAG INDUSTRY CO LTD
CHAOZHOU SUKE PATE SANITARY WARE CO LTD
CHECKEY/KOTOO LEATHER GOODS
CHENGHAI MK TOYS CO LTD
CHEQUEMATES
CHER LEE LONG PACKING INDUSTRY CO LTD
CHINA ELETA TECHNICAL CO LTD
CHINA GOLD PRINTING GROUP LIMITED
CHINESE-PRINTING CO LTD
CHOICE DEVELOPMENT INC
CHROMAPRINT INDIA PRIVATE LTD
CITY SHELVING & STORAGE SYSTEMS
CIXI CITY SMALL SAILBOAT STATIONERY CO LTD
CIXI WEIER PLASTIC CO LTD
CLEVER TRADE PRODUCTS
CMYK HUB
COMPUFIX TAS
COMPUFIX TAS
CONTEXT STATIONERY CO LTD
COPE SENSITIVE FREIGHT
CORPORATE EXPRESS
COURTNEY
CTI COLOUR PRINTERS
CUSTOME-USB INTERNATIONAL CO LTD
D & W INDUSTRY (ASIA) LIMITED
DARK HORSE PRINT DESIGN
DASTEK CORPORATOPN LIMITED
DATAFLOW BUSINESS SYSTEMS
DEBBIE JOSEPH
DEEJAY SIGNS
DHL EXPRESS
DIGI LABELS
DISK BANK
DISK BANK
DISPLAY POWER
DOCKETS AND FORMS PTY LTD
DONG QIAN LAKE INDUSTRIAL CO LTD
DONG YANG JIRONG PLASTIC INDUSTRIAL CO LTD
DONGGUAN CITY JINGLI CAN CO LTD
DONGGUAN KLT & CASINE ELECTRONIC TERCHNOLOGY 
DONGGUAN SHUNTONG COLOR PRINTING CO LTD
DREAMTIME STOCK IMAGES
DUO TRADING
E-PROMO CO LTD
E-STAMPS
EK INTERNATIONAL DEVELOPMENT CO LTD
ELECTRON KINGDOM CO LTD 
ELITE MOLD (SHENZHEN) CO LTD
ENVOPRINT
EURO SIGNS
EVERBEST PRINTING CO LTD
FC PRODUCTIONS
FENG HUA SHUNFA ARTS & CRAFTS CO LTD
FENG YUAN STATIONERY
FENGHUA TECHNOLOGY DEVELOPMENT CO LTD
FENGLOU PACKAGING & COLOUR PRINTING CO LTD
FIRST PACK
FLUIDLINE PTY LTD
FLYING COLOURS
FOILMASTERS
FOOT & PLAYSTED
FOXCIL
FOYER PRINTING
FRANKLIN DIRECT
FRIDGE MAGNET FACTORY
FUZHOU GREEN TRADING CO LTD
G BOOK WRITING MATERIALS
GARETH HOWARD
GLJ LEDGER BAG MAKING FACTORY
GLOBAL MARKET GROUP (ASIA) LTD
GOLDBERRYBRONZE PTY LTD
GOOD FLAG BIOTECHNOLOGY CORPORATION
GRAPHFIX SOLUTIONS
GRAPHIX LABELS PTY LTD
GREENLAND MANUFACTURING & TRADING CO LTD
GTL LIGHTING TECHNOLOGY LTD
GUANG LI PAPER PDTS LTD
GUANG ZHOU SUNSHINE ELECTRONIC TECHNOLOGY CO 
GUANGDONG BAOKE STATIONERY CO LTD
GUANGDONG CLIPLEY ELECTRICAL INDUSTRIAL CO LT
GUANGDONG TENGEN PRINTING CO LTD
GUANGZHOU ANHORN INDUSTRIAL DEV CO LTD
GUANGZHOU HOTIME PRINTING CO LTD
GUANGZHOU HUIDUO ADVERTISING CO LTD
GUANGZHOU KINGSONS LEATHER PRODUCTS CO LTD
GUANGZHOU LETIAN PEN CO LTD
GUANGZHOU LEVON SURPLUS PHOTOELECTRIC CO LTD
GUANGZHOU LICAI ADVERTISEMENT PRODUCTS
GUANGZHOU YANGLING ELECTRONIC SCIENCE & TECHN
GUANGZHOU YINGMEI CRAFTS CO LTD
GUANGZHOU YX PACKAGING PRODUCTS INDUSTRY CO L
GUANGZHOU YXIANG PRINTING CO LTD
GUMMING & VARNISHING SERVICES PTY LTD
GUZHEN BAISHENG STATIONERY CO LTD
H&C PRINTING CENTER LTD
HANGZHOU TIGER ELECTRON & ELECTRIC CO LTD
HAOYUAN ELECTRICAL LIGHTING FACTORY
HEBEI LIGHT INDUSTRIAL PRODUCTS IMP & EXP GRO
HEFEI HENGXIN ENVIRONMENTAL SCIENCE & TECH CO
HEI LONG JIANG CHANNEL INTERNATIONAL TRADE CO
HEIDELBERG GRAPHIC EQUIPMENT PTY LTD
HENAN JIAOZUO FOREIGN TRADE CORP
HENAN LIGHT IND PRODUCTS IMPORT & EXPORT CO L
HENAN PREMTEC ENTERPRISE CORPORATION
HENRY NISSICK
HERBEN NUMBERING SYSTEMS
HEROPRINT
HIGHGATE GROUP
HIPPO BIN
HOBART HARDCHROME PTY LTD
HOMI LIGHTING CO LTD
HONG KONG DIANYI INDUSTRIAL CO LTD
HONG KONG JNHE PAPER CO LTD
HONG KONG TOTAL INDUSTRY
HONGRUNDA (RUIAN) PHOTO ELECTRIC CO LTD
HUAYI LIGHTING COMPANY LIMITED
HUBEI PROVINCIAL LIGHT INDUSTRIAL PRODUCTS IM
HUNAN DERUO TRADE CO LTD
HUNAN FAMOUS TRADING CO LTD
HYGRADE CUTTING FORMES
I-LOVEPRINT CO LTD
IBS CARDS
INTUIT TECHNOLOGIES
ISO PRINTING
ISTOCKPHOTO
J L LENNARD PTY LTD
JCS DIGITAL SOLUTION
JIANGSU HIGH HOPE INTERNATIONAL GROUP
JIANGSU SANTU GROUP CO LTD
JIANGSU SHENGHUI LIGHTING & ELECTRONICS CO LT
JIANGXI HUACAI PRINTING CO LTD
JIANGXI LIANCHUANG OPTO-ELECTRONIC SCIENCE & 
JILIN PROVINCE BLUE AND GREEN WINE CO LTD
JINYI PAPER PRODUCTS & PRINTING CO LTD
JIUN YO CO LTD
JIXIANG DECORATING & CRAFTS FACTORY CO LTD
JOHN HOLTZCLAW
JUIZHOU GREEBLE 
K W  DOGGETT FINE PAPER
KALAMAZOO
KANPRINT
KEEUP PROMOTIONAL LTD
KING HOW LIMITED
KING PRINT
KING YUAN FU PACKING CO LTD
KWALITY PRINTING & STATIONERY
KWIK KOPY
L T PROMOTION TOY CO LTD
LABEL LINE PTY LTD
LABEL NAMES
LABEL POWER
LABELPRESS PTY LTD
LAMSON PARAGON
LEP COLOUR PRINTERS
LEVON SURPLUS (PEIYING) OPTOELECTRONIC CO LTD
LIAONING BAOLIN GROUP ENERGY -SAVING TECH CO 
LITHOTECH INTERNATIONAL
LIZ SMEEKS CONSULTING
LOGO CARPET
LOGOSON ARTS & CRAFTS CO LTD
LONGPACK CO LTD
LOUFOR STATIONERY MANUFACTURING CO LTD
LP PHOTOGRAPHY
LUMEN LED CO LIMITED
LUMIX LIGHTING & ELECTRICAL CO LTD
M & M BINDERS PTY LTD 
M2 STUDIO
MAC PLUS MORE 
MAC SOLUTIONS
MADE-IN-CHINA
MAGNET EXPRESS
MAGNETS.COM.AU
MAILHOUSE TAS DISTRIBUTION SERVICES
MAN FERROSTAAL PTY LTD
MARK MEDIA
MARSDEN BROTHERS
MCPHERSON BOOKBINDERS
MCPHERSONS PRINTING GROUP
MENG HUAN PLUSH TOYS
MERCURY WALCH PTY LTD
MIDAS PRINTING INTERNATIONAL LTD
MOIRS PAPER
MONOTONE ART PRINTERS
MORNING PRINT
MULLER MARTINI AUSTRALIA PTY LTD
MY STICKER FACTORY
NEW STAR CRAFTS CO LTD
NINGBO BIN BIN STATIONERY CO LTD
NINGBO FINELIFE PRODUCTS CO LTD
NINGBO GELANTE ELECTRIC CO LTD
NINGBO HIKING ENTERPRISE CO LTD
NINGBO KAIXIANG ELECTRICAL APPLIANCE CO LTD
NINGBO LUCKY CRAFT CO LTD
NINGBO SHINSKY ELECTRICAL APPLIANCE CO LTD
NINGBO TOPCOM LIGHTING CO LTD
NINGBO YAMAO LIGHTING ELECTRIC APPLIANCE CO L
NINGBO YONGTAI METAL PRODUCTS CO LTD
NINGHAI HUIHUI STATIONERY CO LTD
NINGHAI ZELYNN STATIONERY CO LTD
OFFICE NATIONAL
OFFICE WORKS
ONSITE BELTING
PAC HOLDINGS PTY LTD
PACK QUEEN
PACKAGING PLUS
PAPER ROLLS AUSTRALIA PTY LTD
PAPERLINX OFFICE
PENDA INTERNATIONAL TRADING CO LTD
PLASTIC PASSPORT
PLATYPUS GRAPHICS
PML PRINT
PNS GRAPHICS AUSTRALIA PTY LTD
POWERBEAUTY (DONGGUAN) INDUSTRIAL CO LTD
PRESTIGE BOOKBINDERS
PRESTIGE COURIERS
PRINT BOUND
PRINTERS CHOICE PTY LTD
PRINTING AUTHORITY
PRIORITY CARGO AUST PTY LTD
PROMOTION PRODUCTS
QINGDAO HUALONG PACKING CO LTD
QPS ELECTRONICS CO LTD
QUALITY BINDERS
QUANZHOU QUANKANG CRAFT CO LTD
RAYSON GLOBAL CO LTD
READY STEADY PRINT
RED & BLUE COLOR PRINTING CO LTD
RENOMA PRINTERY
RMV (QUANZHOU) INTERNATIONAL TRADING CO LTD
ROASTAR
ROLLMAKERS PTY LTD
S W GRAPHICS
SAILING INTERNATIONAL LIMITED
SALMAT LETTERBOX DROP SERVICES
SANMAR INDUSTRIAL SUPPLIES
SCORPION PRECISION INDUSTRY (HK) CO LTD
SCREENSPRINT
SEAGA (VIC) PTY LTD
SHANGHAI BAGIFT ARTWARE CO LTD
SHANGHAI DAHUA STATIONERY & SPORTING GOODS FA
SHANGHAI DENGQING IMP & EXP CO LTD
SHANGHAI FOREST PACKING CO LTD
SHANGHAI GOODWIEW ELECTRONIC CO LTD
SHANGHAI HONGTUO ECO-TECHNOLOGY CO LTD
SHANGHAI SUNKEA PAPER CUP CO LTD
SHANTOU BO CHUAN MACHINERY CO LTD
SHANTOU CHENGHAI HUAJUN AERMODELLING & PLASTI
SHANTOU WEIZIN INDUSTRIAL CO LTD
SHANTOU XITONG STATIONERY INDUSTRY CO LTD
SHEA PLASTICS
SHENZHEN ANDASHENG BAG MANUFACTURING CO LTD
SHENZHEN AOJIN HANDBAG CO LTD
SHENZHEN CHUANGXINJIA RFID TAG CO LTD
SHENZHEN FLEXWILL CO LTD
SHENZHEN FONACA TECH
SHENZHEN GUTON TECHNOLOGY CO LTD
SHENZHEN LANCER ELECTRONIC CO LTD
SHENZHEN NEW JIN KE CYBER DEVELOPING CO LTD
SHENZHEN SANFENG PLASTIC PACKING CO LTDSANFEN
SHENZHEN SCOPE SCIENTIFIC DEVELOPMENT CO LTD
SHENZHEN SEMILUX LIGHTING TECHNOLOGY CO LTD
SHENZHEN SHINEWAY LTD
SHENZHEN SUNLANRFID TECHNOLOGY CO LTD
SHENZHEN SUNLIGHT ELECTRONIC TECHNOLOGY CO LT
SHENZHEN SUPERTAI TECHNOLOGY CO LTD
SHENZHEN TOP TECHNOLOGY CO LTD
SHENZHEN WANIDA TECHNOLOGY CO LTD
SHENZHEN XINGZHIYE PRINTING & PACKING CO LTD
SHENZHEN ZHONGHENGHUA TECHNOLOGY CO LTD 
SHUNKI TECHNOLOGY CO LTD
SIGNWORKS
SINO PATH ENTERPRISES LIMITED
SLIMLINE WAREHOUSE
SMARTEE
SOCIAL PRINTING PTY LTD
SOUTHERN SAW SERVICE
SPEEDY
SPICERS HOBART
ST VINCENT DE PAUL
STANDOUT MATS PTY LTD
STAR TRACK
STICKER COMPANY
STRAPMARK PTY LTD
STS SANTUCCI TAILORED SERVICES PTY LTD.
STUART AGAR EQUIPMENT SERVICES
STYGIAN STUDIO
SUN-FLY
SUNLIGHT ELECTRONIC TECHNOLOGY CO LTD
SUNNY & SANDY CRAFTS CO LTD
SUNNY YOUNG ENTERPRISE CO LTD
TADPAC PRINT
TAGS & TICKETS
TAI ZHOU GODDESS PLAYING CARDS CO LTD
TAIZHOU IDEAPAD STATIONERY CO LTD
TASMANIAN FREIGHT SERVICES PTY LTD
TENDER INTERNATIONAL CO LTD
TENG FEI INTERNATIONAL DEVELOPMENT LTD
TEST SUPPLIER
TEST SUPPLIER2
THE POLYTHENE COMPANY
THE SIGN & PRINT SHOP
THE WORKS PRINTING GROUP PTY LTD
TIEN WAH PRESS (PTE) LIMITED
TIM CARTER
TLC DIGITAL +
TONGLU AI-DE IMP & EXP CO LTD
TOP PRINT
TOTAL NETWORKS
TOURISM BROCHURE EXCHANGE
TRADEKOREA.COM
TST PRINTING
TUNG YUNG INTERNATIONAL LIMITED
TYPEFACE
Test supplier
USB BOOK COMPANY LTD
USB SKY ELECTRONIC TECHNOLOGY CO LTD
USB-LIFETIME ELECTRONIC TECHNOLOGY CO LTD
VISTAPRINT
WAH SHING PACKING PRODUCTS CO LTD
WALKABOUT ENTERPRISES
WASSYS TRNSPORT
WEIFANG TOPSUN TEXTILE CO LTD
WELSON MOLD (HONG KONG) CO LTD
WENZHOU DIVINE LAND DECORATION LIGHT CO LTD
WENZHOU GUANGXIN PACKAGING CO LTD
WENZHOU SUCCESS GROUP CO LTD
WENZHOU TIANHAO PEN INDUSTRIAL CO LTD
WENZHOU TREASURE CRAFTS CO LTD
WENZHOUSHENGCAIGONGYILIPINCHANG
WENZHOUY FEIYA STATIONERY CO LTD
WHOLE VIEW SUPPLY CHAIN MANAGEMENT CO LTD
WINBO INDUSTRIAL CO LTD
XIAMEN BONSTAR BAGS CO LTD
XIAMEN HAIRISHENG NON WOVEN PRIDUCTS LTD
XIAMEN NOVELTY FLAG CO LTD
XIAMEN WISELINK INDUSTRY & TRADE CO LTD
XIAYI COUNTY SHENGONG PEN IDUSTRY CO LTD
XING CHEN HAT INDUSTRY CO LTD
YESING LABEL COMPANY
YIWU BAILONG ELECTRICAL APPLIANCE CO LTD
YIWU CITY JIANPING SCHOOL SUPPLY AND STATIONE
YIWU HANFENG HANDBAG CO LTD
YIWU HUA DA STATIONERY FIRM
YIWU SHUANGDELI COLOR PRINTING FACTORY
YIWU WAHU GIFT PACKING CO LTD
YIWU XIAO BO SHI STATIONERY CO LTD
YIWU XINGQIBA TOY BUSINESS
YIWU ZHUO YUAN PACKAGING  FACTORY
YOUNG SUN TRADING CO LTD
ZHANGJIAGANG JINGGONG PACKAGING & COLOR PRINT
ZHEJIANG HUAXU INDUSTRIAL CO LTD
ZHEJIANG OTOR CONTAINER TECHNOLOGY CO LTD
ZHEJIANG SANBAO PRINTING CO LTD
ZHEJIANG VOLONG SANITARY WARES CO LTD
ZHEJINAG YIWU BAOLONG WRAPPING S&T CO LTD
ZHONGQIAN LIGHTING
ZHONGSHAN LEADER LIGHTING TECHNOLOGY CO LTD
ZHONGSHAN NORSLAN LIGHTING & ELECTRONICS CO L
") as $supplier_name){
        Supplier::create(['supplier_name' => $supplier_name]);
    }

        $franklin = Supplier::where('supplier_name', '=', 'FRANKLIN DIRECT')->firstOrFail();
        $compufix = Supplier::where('supplier_name', '=', 'COMPUFIX TAS')->firstOrFail();

        

        SupplierContact::create(['supplier_id' => $franklin->id, 
                                 'first_name' => 'David', 
                                 'last_name' => 'Thorne',
                                 'email' => 'art@franklindirect.com.au']);

        SupplierContact::create(['supplier_id' => $compufix->id, 
                                 'first_name' => 'Craig', 
                                 'last_name' => 'Marshall',
                                 'email' => 'craig9@gmail.com']);
    }
}

